function rgbToHex(r,g,b){return '#'+[r,g,b].map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('').toUpperCase()}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h=0,s=0,l=(max+min)/2;if(max!==min){const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h*=60}return[Math.round(h),Math.round(s*100),Math.round(l*100)]}
function colorName(r,g,b){if(r>220&&g>220&&b>220)return'White';if(r<45&&g<45&&b<45)return'Black';if(Math.max(r,g,b)-Math.min(r,g,b)<18)return r<100?'Dark Gray':r>200?'Light Gray':'Gray';if(r>200&&g<110&&b<110)return'Red';if(r>200&&g>150&&b<100)return'Yellow';if(r>200&&g>80&&g<180&&b<80)return'Orange';if(g>150&&r<120&&b<140)return'Green';if(b>160&&r<130&&g<150)return'Blue';if(r>150&&b>130&&g<120)return'Purple';if(r>180&&b>150&&g<150)return'Pink';if(r>100&&g>60&&b<70)return'Brown';return'Custom Color'}
function copyText(text){if(navigator.clipboard)navigator.clipboard.writeText(text)}
function saveColor(color){const a=JSON.parse(localStorage.getItem('colorlessSavedColors')||'[]');if(!a.some(c=>c.hex===color.hex)){a.unshift(color);localStorage.setItem('colorlessSavedColors',JSON.stringify(a.slice(0,40)))}return a}
function extractPalette(image,count=6){const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});const scale=Math.min(160/image.naturalWidth,160/image.naturalHeight,1);c.width=Math.max(1,Math.round(image.naturalWidth*scale));c.height=Math.max(1,Math.round(image.naturalHeight*scale));x.drawImage(image,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data,b=new Map();for(let i=0;i<d.length;i+=16){const r=Math.min(255,Math.round(d[i]/32)*32),g=Math.min(255,Math.round(d[i+1]/32)*32),bl=Math.min(255,Math.round(d[i+2]/32)*32),k=r+','+g+','+bl;b.set(k,(b.get(k)||0)+1)}return[...b.entries()].sort((a,z)=>z[1]-a[1]).slice(0,count).map(([k])=>{const[r,g,b]=k.split(',').map(Number);return{r,g,b,hex:rgbToHex(r,g,b),name:colorName(r,g,b)}})}

window.addEventListener('load',()=>{const image=document.getElementById('editorImage'),stage=document.getElementById('stage'),box=document.getElementById('cropBox');if(!image||!stage||!box)return;let ratio=null,overlay=null,selection=null,drag=null;
function closeCrop(){if(overlay){overlay.remove();overlay=null}selection=null;drag=null}
function openCrop(value){ratio=value==='free'?null:parseFloat(value);if(!Number.isFinite(ratio))ratio=null;closeCrop();overlay=document.createElement('div');overlay.className='crop-overlay';overlay.innerHTML='<div class="crop-head"><strong>Crop reference</strong><span id="cropSize"></span></div><div class="crop-frame"><img class="crop-source" alt=""><div class="crop-selection"><i class="crop-handle nw"></i><i class="crop-handle ne"></i><i class="crop-handle sw"></i><i class="crop-handle se"></i></div></div><div class="crop-actions"><button type="button" id="cropCancel">Cancel</button><button type="button" class="primary" id="cropApply">Apply crop</button></div>';document.body.appendChild(overlay);const frame=overlay.querySelector('.crop-frame'),source=overlay.querySelector('.crop-source'),sel=overlay.querySelector('.crop-selection'),size=overlay.querySelector('#cropSize');source.src=image.src;frame.style.aspectRatio=(image.naturalWidth||1)+' / '+(image.naturalHeight||1);function bounds(){return{w:frame.clientWidth,h:frame.clientHeight}}function paint(){if(!selection)return;sel.style.left=selection.x+'px';sel.style.top=selection.y+'px';sel.style.width=selection.w+'px';sel.style.height=selection.h+'px';size.textContent=Math.round(selection.w)+' × '+Math.round(selection.h)}function fit(){const q=bounds();let w=q.w*.78,h=q.h*.78;if(ratio){if(w/h>ratio)w=h*ratio;else h=w/ratio}selection={x:(q.w-w)/2,y:(q.h-h)/2,w,h};paint()}fit();
function point(e){const p=e.touches?e.touches[0]:e,r=frame.getBoundingClientRect();return{x:p.clientX-r.left,y:p.clientY-r.top}}
function begin(e,type){e.preventDefault();e.stopPropagation();drag={type,start:point(e),base:{...selection}};e.currentTarget.setPointerCapture?.(e.pointerId)}
sel.addEventListener('pointerdown',e=>{if(!e.target.classList.contains('crop-handle'))begin(e,'move')});sel.querySelectorAll('.crop-handle').forEach(h=>h.addEventListener('pointerdown',e=>begin(e,h.className.split(' ')[1])));
sel.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y,b=drag.base,q=bounds();let n={...b};if(drag.type==='move'){n.x=Math.max(0,Math.min(q.w-b.w,b.x+dx));n.y=Math.max(0,Math.min(q.h-b.h,b.y+dy))}else{let left=b.x,top=b.y,right=b.x+b.w,bottom=b.y+b.h;if(drag.type.includes('w'))left=Math.min(right-50,Math.max(0,b.x+dx));if(drag.type.includes('e'))right=Math.max(left+50,Math.min(q.w,b.x+b.w+dx));if(drag.type.includes('n'))top=Math.min(bottom-50,Math.max(0,b.y+dy));if(drag.type.includes('s'))bottom=Math.max(top+50,Math.min(q.h,b.y+b.h+dy));let w=right-left,h=bottom-top;if(ratio){if(Math.abs(dx)>=Math.abs(dy)){w=Math.max(50,Math.min(q.w-left,w));h=w/ratio}else{h=Math.max(50,Math.min(q.h-top,h));w=h*ratio}if(drag.type.includes('w'))left=b.x+b.w-w;if(drag.type.includes('n'))top=b.y+b.h-h;if(left<0){left=0;w=Math.min(w,q.w);h=ratio?w/ratio:h}if(top<0){top=0;h=Math.min(h,q.h);w=ratio?h*ratio:w}if(left+w>q.w){w=q.w-left;h=w/ratio}if(top+h>q.h){h=q.h-top;w=h*ratio}}n={x:left,y:top,w:Math.min(w,q.w-left),h:Math.min(h,q.h-top)}}selection=n;paint()});['pointerup','pointercancel'].forEach(t=>sel.addEventListener(t,()=>drag=null));
overlay.querySelector('#cropCancel').onclick=closeCrop;overlay.querySelector('#cropApply').onclick=()=>{const q=bounds(),left=Math.max(0,selection.x),top=Math.max(0,selection.y),right=Math.min(q.w,selection.x+selection.w),bottom=Math.min(q.h,selection.y+selection.h),sx=image.naturalWidth/q.w,sy=image.naturalHeight/q.h,x=Math.round(left*sx),y=Math.round(top*sy),w=Math.max(1,Math.round((right-left)*sx)),h=Math.max(1,Math.round((bottom-top)*sy)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(image,x,y,w,h,0,0,w,h);if(typeof push==='function')push();image.src=c.toDataURL('image/jpeg',.94);image.onload=()=>{if(typeof drawGrid==='function')drawGrid();closeCrop()}}}
document.querySelectorAll('#cropPanel [data-ratio]').forEach(b=>b.addEventListener('click',()=>openCrop(b.dataset.ratio)));box.innerHTML='<p style="color:#777;margin:0">Choose a ratio above to open the crop workspace.</p>';
const style=document.createElement('style');style.textContent='.crop-overlay{position:fixed;inset:0;z-index:9999;background:rgba(5,5,7,.97);display:flex;flex-direction:column;padding:12px;touch-action:none}.crop-head{display:flex;justify-content:space-between;align-items:center;color:#fff;padding:6px 2px 12px}.crop-head span{color:#aaa;font-size:12px}.crop-frame{position:relative;width:min(100%,900px);max-height:calc(100vh - 115px);margin:auto;background:#111;overflow:hidden;border-radius:14px;display:flex;align-items:center;justify-content:center}.crop-source{width:100%;height:100%;object-fit:contain;display:block}.crop-selection{position:absolute;border:1px solid rgba(255,255,255,.92);box-shadow:0 0 0 9999px rgba(0,0,0,.45);touch-action:none}.crop-selection:before,.crop-selection:after{content:"";position:absolute;pointer-events:none}.crop-selection:before{left:33.333%;right:33.333%;top:0;bottom:0;border-left:1px solid rgba(255,255,255,.22);border-right:1px solid rgba(255,255,255,.22)}.crop-selection:after{top:33.333%;bottom:33.333%;left:0;right:0;border-top:1px solid rgba(255,255,255,.22);border-bottom:1px solid rgba(255,255,255,.22)}.crop-handle{position:absolute;width:18px;height:18px;border:2px solid #fff;background:rgba(0,0,0,.3);border-radius:50%;z-index:2}.crop-handle.nw{left:-10px;top:-10px}.crop-handle.ne{right:-10px;top:-10px}.crop-handle.sw{left:-10px;bottom:-10px}.crop-handle.se{right:-10px;bottom:-10px}.crop-actions{display:flex;gap:10px;justify-content:flex-end;padding:12px 0 2px}.crop-actions button{min-width:110px}@media(max-width:600px){.crop-overlay{padding:9px}.crop-actions button{flex:1}}';document.head.appendChild(style)})