function rgbToHex(r,g,b){return '#'+[r,g,b].map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('').toUpperCase()}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h=0,s=0,l=(max+min)/2;if(max!==min){const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h*=60}return[Math.round(h),Math.round(s*100),Math.round(l*100)]}
function colorName(r,g,b){if(r>220&&g>220&&b>220)return'White';if(r<45&&g<45&&b<45)return'Black';if(Math.max(r,g,b)-Math.min(r,g,b)<18)return r<100?'Dark Gray':r>200?'Light Gray':'Gray';if(r>200&&g<110&&b<110)return'Red';if(r>200&&g>150&&b<100)return'Yellow';if(r>200&&g>80&&g<180&&b<80)return'Orange';if(g>150&&r<120&&b<140)return'Green';if(b>160&&r<130&&g<150)return'Blue';if(r>150&&b>130&&g<120)return'Purple';if(r>180&&b>150&&g<150)return'Pink';if(r>100&&g>60&&b<70)return'Brown';return'Custom Color'}
function copyText(text){if(navigator.clipboard)navigator.clipboard.writeText(text)}
function saveColor(color){const a=JSON.parse(localStorage.getItem('colorlessSavedColors')||'[]');if(!a.some(c=>c.hex===color.hex)){a.unshift(color);localStorage.setItem('colorlessSavedColors',JSON.stringify(a.slice(0,40)))}return a}
function extractPalette(image,count=6){const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});const scale=Math.min(160/image.naturalWidth,160/image.naturalHeight,1);c.width=Math.max(1,Math.round(image.naturalWidth*scale));c.height=Math.max(1,Math.round(image.naturalHeight*scale));x.drawImage(image,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data,b=new Map();for(let i=0;i<d.length;i+=16){const r=Math.min(255,Math.round(d[i]/32)*32),g=Math.min(255,Math.round(d[i+1]/32)*32),bl=Math.min(255,Math.round(d[i+2]/32)*32),k=r+','+g+','+bl;b.set(k,(b.get(k)||0)+1)}return[...b.entries()].sort((a,z)=>z[1]-a[1]).slice(0,count).map(([k])=>{const[r,g,b]=k.split(',').map(Number);return{r,g,b,hex:rgbToHex(r,g,b),name:colorName(r,g,b)}})}

/* COLORLESS crop tool: a mobile-friendly, non-destructive crop overlay with free and fixed aspect ratios. */
window.addEventListener('load',()=>{const image=document.getElementById('editorImage'),stage=document.getElementById('stage'),box=document.getElementById('cropBox');if(!image||!stage||!box)return;let ratio=null,overlay=null,selection=null,drag=null;
function openCrop(r){ratio=r==='free'?null:parseFloat(r);if(!Number.isFinite(ratio))ratio=null;closeCrop();overlay=document.createElement('div');overlay.className='crop-overlay';overlay.innerHTML='<div class="crop-head"><strong>Crop reference</strong><span id="cropSize"></span></div><div class="crop-frame"><div class="crop-selection"><i class="crop-handle nw"></i><i class="crop-handle ne"></i><i class="crop-handle sw"></i><i class="crop-handle se"></i></div></div><div class="crop-actions"><button type="button" id="cropCancel">Cancel</button><button type="button" class="primary" id="cropApply">Apply crop</button></div>';document.body.appendChild(overlay);const frame=overlay.querySelector('.crop-frame'),sel=overlay.querySelector('.crop-selection'),size=overlay.querySelector('#cropSize');const fr=()=>{const w=frame.clientWidth,h=frame.clientHeight;return{w,h}};function fit(){const{w,h}=fr();let sw=w*.78,sh=h*.78;if(ratio){if(sw/sh>ratio)sw=sh*ratio;else sh=sw/ratio}selection={x:(w-sw)/2,y:(h-sh)/2,w:sw,h:sh};paint()}
function paint(){if(!selection)return;const s=selection;sel.style.left=s.x+'px';sel.style.top=s.y+'px';sel.style.width=s.w+'px';sel.style.height=s.h+'px';size.textContent=Math.round(s.w)+' × '+Math.round(s.h)}fit();window.addEventListener('resize',fit,{once:true});
function point(e){const p=e.touches?e.touches[0]:e;const r=frame.getBoundingClientRect();return{x:p.clientX-r.left,y:p.clientY-r.top}}
sel.addEventListener('pointerdown',e=>{if(e.target.classList.contains('crop-handle'))return;drag={type:'move',start:point(e),base:{...selection}};sel.setPointerCapture(e.pointerId)});sel.querySelectorAll('.crop-handle').forEach(h=>h.addEventListener('pointerdown',e=>{e.stopPropagation();drag={type:h.className.split(' ')[1],start:point(e),base:{...selection}};h.setPointerCapture(e.pointerId)}));sel.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y,b=drag.base,{w,h}=fr();let n={...b};if(drag.type==='move'){n.x=Math.max(0,Math.min(w-b.w,b.x+dx));n.y=Math.max(0,Math.min(h-b.h,b.y+dy))}else{let nw=b.w,n h=b.h;let left=b.x,top=b.y;if(drag.type.includes('e'))nw=b.w+dx;if(drag.type.includes('w')){nw=b.w-dx;left=b.x+dx}if(drag.type.includes('s'))nh=b.h+dy;if(drag.type.includes('n')){nh=b.h-dy;top=b.y+dy}if(ratio){if(Math.abs(dx)>=Math.abs(dy))nh=nw/ratio;else nw=nh*ratio;if(drag.type.includes('w'))left=b.x+b.w-nw;if(drag.type.includes('n'))top=b.y+b.h-nh}nw=Math.max(60,Math.min(w-left,nw));nh=Math.max(60,Math.min(h-top,nh));n={x:left,y:top,w:nw,h:nh};if(n.x<0)n.x=0;if(n.y<0)n.y=0}selection=n;paint()});['pointerup','pointercancel'].forEach(t=>sel.addEventListener(t,()=>drag=null));overlay.querySelector('#cropCancel').onclick=closeCrop;overlay.querySelector('#cropApply').onclick=apply;}
function apply(){if(!selection)return;const frame=overlay.querySelector('.crop-frame'),fr=frame.getBoundingClientRect(),ir=image.getBoundingClientRect();const scaleX=image.naturalWidth/ir.width,scaleY=image.naturalHeight/ir.height;const left=Math.max(0,(fr.left+selection.x-ir.left)*scaleX),top=Math.max(0,(fr.top+selection.y-ir.top)*scaleY),right=Math.min(image.naturalWidth,(fr.left+selection.x+selection.w-ir.left)*scaleX),bottom=Math.min(image.naturalHeight,(fr.top+selection.y+selection.h-ir.top)*scaleY);const w=Math.max(1,Math.round(right-left)),h=Math.max(1,Math.round(bottom-top));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(image,left,top,w,h,0,0,w,h);if(typeof push==='function')push();image.src=c.toDataURL('image/jpeg',.94);image.onload=()=>{if(typeof drawGrid==='function')drawGrid();closeCrop()};}
function closeCrop(){if(overlay){overlay.remove();overlay=null}selection=null}
document.querySelectorAll('#cropPanel [data-ratio]').forEach(b=>b.addEventListener('click',()=>openCrop(b.dataset.ratio)));box.innerHTML='<p style="color:#777;margin:0">Choose a ratio above to open the crop workspace.</p>';
const style=document.createElement('style');style.textContent='.crop-overlay{position:fixed;inset:0;z-index:9999;background:rgba(5,5,7,.96);display:flex;flex-direction:column;padding:14px;touch-action:none}.crop-head{display:flex;justify-content:space-between;align-items:center;color:#fff;padding:6px 2px 12px}.crop-head span{color:#aaa;font-size:12px}.crop-frame{position:relative;flex:1;min-height:0;max-width:900px;width:100%;margin:auto;background:#111 url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%2724%27 height=%2724%27 viewBox=%270 0 24 24%27%3E%3Cpath fill=%27%23333%27 d=%27M0 0h1v1H0zM12 12h1v1h-1zM23 23h1v1h-1z%27/%3E%3C/svg%3E);overflow:hidden;border-radius:14px}.crop-frame:before{content:"";position:absolute;inset:0;background:rgba(0,0,0,.28);pointer-events:none}.crop-selection{position:absolute;border:1px solid rgba(255,255,255,.9);box-shadow:0 0 0 9999px rgba(0,0,0,.42);touch-action:none}.crop-selection:before,.crop-selection:after{content:"";position:absolute;inset:33.333% 0;border-top:1px solid rgba(255,255,255,.22);border-bottom:1px solid rgba(255,255,255,.22);pointer-events:none}.crop-selection:after{inset:0 33.333%;border-top:0;border-bottom:0;border-left:1px solid rgba(255,255,255,.22);border-right:1px solid rgba(255,255,255,.22)}.crop-handle{position:absolute;width:18px;height:18px;border:2px solid #fff;background:rgba(0,0,0,.25);border-radius:50%;z-index:2}.crop-handle.nw{left:-10px;top:-10px}.crop-handle.ne{right:-10px;top:-10px}.crop-handle.sw{left:-10px;bottom:-10px}.crop-handle.se{right:-10px;bottom:-10px}.crop-actions{display:flex;gap:10px;justify-content:flex-end;padding:14px 0 2px}.crop-actions button{min-width:110px}@media(max-width:600px){.crop-overlay{padding:10px}.crop-actions button{flex:1}}';document.head.appendChild(style);
});